# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Denver Concerts App CI/CD

on:
  push:
    branches:
      - main

jobs:
  # Continuous Integration
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Unit Tests
        env:
          SQLITE_DATABASE_URI: ${{ secrets.SQLITE_DATABASE_URI }}
          TICKETMASTER_DISCOVERY_API_KEY: ${{ secrets.TICKETMASTER_DISCOVERY_API_KEY }}
        run: python -m unittest discover -s tests/unit -p '*_test.py'
      - name: Run Integration Tests
        env:
          SQLITE_DATABASE_URI: ${{ secrets.SQLITE_DATABASE_URI }}
          TICKETMASTER_DISCOVERY_API_KEY: ${{ secrets.TICKETMASTER_DISCOVERY_API_KEY }}
        run: python -m unittest discover -s tests/integration -p '*_test.py'

  # Continuous Deployment
  # https://github.com/marketplace/actions/deploy-to-heroku
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "denver-concert-app"
          heroku_email: ${{secrets.ADMIN_EMAIL}}
